# Generated by Django 5.0.6 on 2024-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_command_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='commend_count',
            field=models.IntegerField(default=0),
        ),
    ]
